//! Compile-time param gate (apex-ayl.130 ZC-PARAMSCHEMA-GATE-1, P1):
//! param drift = compile failure.
//!
//! Enforced surface (model rows):
//!   - `DefaultModelEntry` struct fields <-> `config.schema.json`
//!     `#/definitions/ConfigModelOverride/properties` — reported in BOTH
//!     directions (new struct field w/o schema definition = fail; schema
//!     property w/o struct field = fail, unless explicitly classified);
//!   - `default_models.json` baked row keys stay inside the same surface
//!     (serde would silently drop unmodeled keys);
//!   - `REQUIRED_FIELDS` / `EFFORT_VALUES` are derived here from the schema
//!     (single source of truth — the sibling Python gate, apex-ayl.128,
//!     reads the same schema; no hardcoded copies in this crate).
//!
//! The gate logic lives in `src/param_gate_check.rs` — the same file the
//! `#[cfg(test)]` selftest runs against mutated schemas (std + serde_json
//! only, so both contexts compile it).
//!
//! `GROK_MODELS_PARAMGATE_SCHEMA` overrides the schema path — a test hook so
//! the gate can be exercised end-to-end against a mutated temp schema
//! (repo precedent: `GROK_SHELL_BUNDLE_RG_PATH`).

mod param_gate_check {
    include!("src/param_gate_check.rs");
}
use param_gate_check as gate;

const SCHEMA_RELPATH: &str = "../xai-grok-shell/config.schema.json";

fn read_or_die(path: &std::path::Path, what: &str) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|e| {
        eprintln!(
            "xai-grok-models param-gate: cannot read {what} at {}: {e}",
            path.display()
        );
        std::process::exit(1);
    })
}

fn const_list(values: &[String]) -> String {
    let inner: Vec<String> = values.iter().map(|v| format!("\"{v}\"")).collect();
    format!("&[{}]", inner.join(", "))
}

fn main() {
    let manifest_dir =
        std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));

    println!("cargo:rerun-if-env-changed=GROK_MODELS_PARAMGATE_SCHEMA");
    let schema_path = match std::env::var("GROK_MODELS_PARAMGATE_SCHEMA") {
        Ok(override_path) => {
            let path = std::path::PathBuf::from(override_path);
            println!("cargo:rerun-if-changed={}", path.display());
            path
        }
        Err(_) => {
            println!("cargo:rerun-if-changed={SCHEMA_RELPATH}");
            manifest_dir.join(SCHEMA_RELPATH)
        }
    };
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=default_models.json");

    let schema_text = read_or_die(&schema_path, "config.schema.json");
    let lib_text = read_or_die(&manifest_dir.join("src/lib.rs"), "src/lib.rs");
    let baked_text = read_or_die(
        &manifest_dir.join("default_models.json"),
        "default_models.json",
    );

    let report = gate::run_gate(&schema_text, &lib_text, &baked_text);
    if !report.errors.is_empty() {
        eprintln!(
            "xai-grok-models param-gate: {} param drift error(s) — \
`{}` fields <-> config.schema.json ConfigModelOverride ({}):",
            report.errors.len(),
            gate::STRUCT_NAME,
            if std::env::var("GROK_MODELS_PARAMGATE_SCHEMA").is_ok() {
                "schema override in effect"
            } else {
                SCHEMA_RELPATH
            }
        );
        for error in &report.errors {
            eprintln!("  {error}");
        }
        eprintln!(
            "Fix the drift (struct field <-> schema property <-> baked row key) \
or classify it in src/param_gate_check.rs with a reason."
        );
        std::process::exit(1);
    }

    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let mut generated = String::new();
    generated.push_str(
        "// GENERATED by build.rs (apex-ayl.130 ZC-PARAMSCHEMA-GATE-1, P1). DO NOT EDIT.\n",
    );
    generated.push_str(
        "// Derived at build time from crates/codegen/xai-grok-shell/config.schema.json\n",
    );
    generated.push_str("// (single source of truth; the sibling Python gate reads the same schema).\n");
    generated.push_str(
        "/// `ConfigModelOverride` properties, sorted. The full config-row surface.\n",
    );
    generated.push_str("pub const SCHEMA_PROPERTIES: &[&str] = ");
    generated.push_str(&const_list(&report.schema_properties));
    generated.push_str(";\n\n");
    generated.push_str(
        "/// `DefaultModelEntry` fields, declaration order. The row surface.\n",
    );
    generated.push_str("pub const STRUCT_FIELDS: &[&str] = ");
    generated.push_str(&const_list(&report.struct_fields));
    generated.push_str(";\n\n");
    generated.push_str(
        "/// Curation-required fields: (DefaultModelEntry ∩ schema) minus the\n",
    );
    generated.push_str(
        "/// documented excludes (row identity, free-form prose, C-class generated caps).\n",
    );
    generated.push_str("pub const REQUIRED_FIELDS: &[&str] = ");
    generated.push_str(&const_list(&report.required_fields));
    generated.push_str(";\n\n");
    generated.push_str(
        "/// Canonical effort values (`#/definitions/ReasoningEffort.enum`).\n",
    );
    generated.push_str("pub const EFFORT_VALUES: &[&str] = ");
    generated.push_str(&const_list(&report.effort_values));
    generated.push_str(";\n");

    std::fs::write(out_dir.join("param_gate_generated.rs"), generated).unwrap_or_else(|e| {
        eprintln!("xai-grok-models param-gate: cannot write generated constants: {e}");
        std::process::exit(1);
    });
}
