//! Generated JSON Schema for the `~/.grok/config.toml` surface (agent [`Config`]).
//!
//! Donor: codex (first-hand verified in `upstream/codex`):
//! - `codex-rs/config/src/schema.rs` — `canonicalize` / `config_schema_json` /
//!   `write_config_schema`, ported 1:1 (canonicalize byte-identical).
//! - `codex-rs/core/src/config/schema_tests.rs` — the golden-fixture staleness test
//!   (`config_schema_matches_fixture`), mirrored in `config_schema_tests.rs`.
//! - `codex-rs/config-schema` — the writer bin (here: `--bin config-schema-write`).
//! Adapted to the workspace's schemars 1.x: `SchemaSettings::draft07()` keeps the
//! donor's draft-07 + `/definitions` shape.
//!
//! Surface model: every `Config` field serde reads from config.toml
//! (`#[serde(skip)]` fields are runtime-only and excluded), plus the user-authored
//! `[model.<id>]` override rows — parsed from the raw toml by
//! `parse_model_overrides`, not a serde field — injected as the root `model`
//! property (donor-style post-processing, cf. codex's
//! `add_shell_environment_policy_constraints`).
//!
//! Regenerate the committed fixture:
//! ```sh
//! cargo run -p xai-grok-shell --bin config-schema-write
//! ```
//! The golden test fails with a unified diff + this hint if the live types drift.

use std::path::Path;

use crate::agent::config::{Config, ConfigModelOverride};
use schemars::generate::SchemaSettings;
use schemars::{Schema, SchemaGenerator};
use serde_json::{Map, Value};

/// Annotation written into the generated fixture (JSON Schema `$comment` — the
/// only place a "header" can live in strict JSON).
const REGEN_HINT: &str = "Generated by `cargo run -p xai-grok-shell --bin config-schema-write` \
 from the live config types (xai-grok-shell::agent::config::Config + [model.<id>] rows). \
 Do not edit by hand; the golden test agent::config_schema_tests::config_schema_matches_fixture \
 fails if the types drift. Donor: codex-rs/config/src/schema.rs + codex-rs/config-schema.";

/// Root schema for the config.toml surface of [`Config`].
pub fn config_schema() -> Schema {
    let settings = SchemaSettings::draft07();
    let mut generator = SchemaGenerator::new(settings);
    // Register the model-row type BEFORE the root build: `root_schema_for`
    // snapshots the generator's definitions at that point, so a type first
    // referenced afterwards would dangle.
    generator.subschema_for::<ConfigModelOverride>();
    let mut schema = generator.root_schema_for::<Config>();

    // Inject the `model` root property: `[model.<id>]` override rows are parsed
    // from the raw toml (`parse_model_overrides`), not deserialized as a serde
    // field of `Config`, so the derive cannot see them.
    let row_ref = generator.subschema_for::<ConfigModelOverride>(); // $ref; already registered
    let mut row = Map::new();
    row.insert(
        "description".into(),
        Value::String(
            "Per-model override rows: `[model.<id>]` tables merged over the live model \
             catalog (see ConfigModelOverride)."
                .into(),
        ),
    );
    row.insert("type".into(), Value::String("object".into()));
    row.insert("additionalProperties".into(), row_ref.to_value());
    if let Some(Value::Object(properties)) = schema.ensure_object().get_mut("properties") {
        properties.insert("model".into(), Value::Object(row));
    }

    schema
}

/// Canonicalize a JSON value by sorting its keys recursively (donor 1:1).
pub fn canonicalize(value: &Value) -> Value {
    match value {
        Value::Array(items) => Value::Array(items.iter().map(canonicalize).collect()),
        Value::Object(map) => {
            let mut entries: Vec<_> = map.iter().collect();
            entries.sort_by_key(|(key, _)| *key);
            let mut sorted = Map::with_capacity(map.len());
            for (key, child) in entries {
                sorted.insert(key.clone(), canonicalize(child));
            }
            Value::Object(sorted)
        }
        _ => value.clone(),
    }
}

/// The canonicalized, default-stripped schema value — the single model both
/// the JSON fixture and the HTML reference (`html` module) render from.
///
/// Split out of `config_schema_json` (apex-33z) so the HTML renderer reuses
/// the exact same canonicalize + strip pipeline; the JSON bytes are
/// unchanged (the `config_schema_matches_fixture` golden pins that).
pub fn config_schema_value() -> Value {
    let mut value = canonicalize(&config_schema().to_value());
    strip_defaults(&mut value);
    value
}

/// Render the config schema as canonicalized, pretty-printed JSON.
pub fn config_schema_json() -> serde_json::Result<Vec<u8>> {
    let mut value = config_schema_value();
    if let Value::Object(root) = &mut value {
        root.insert("$comment".into(), Value::String(REGEN_HINT.to_string()));
    }
    Ok(serde_json::to_vec_pretty(&value)?)
}

/// Recursively strip every `default` key from the schema.
///
/// Donor deviation (recorded in the SDD): codex's `Default` impls are pure,
/// so its `default` annotations are reproducible constants. Here several
/// config surfaces (notably `EndpointsConfig`) implement `Default` by reading
/// environment variables, so the derive would bake env-dependent values
/// (internal endpoints, deployment keys) into the fixture. The schema is
/// shape-only, so defaults are stripped at render time.
fn strip_defaults(value: &mut Value) {
    match value {
        Value::Object(map) => {
            // Rebuild the map without `default` keys. Do NOT use
            // `map.remove("default")`: with `serde_json/preserve_order` the
            // map is an `IndexMap`, and indexmap 2.x `remove` is a
            // SWAP-REMOVE that displaces the last key into the removed
            // slot, corrupting the canonicalized key order.
            let mut kept = Map::with_capacity(map.len());
            for (key, child) in std::mem::take(map) {
                if key != "default" {
                    kept.insert(key, child);
                }
            }
            *map = kept;
            for child in map.values_mut() {
                strip_defaults(child);
            }
        }
        Value::Array(items) => items.iter_mut().for_each(strip_defaults),
        _ => {}
    }
}

/// Write the config schema fixture to disk.
pub fn write_config_schema(out_path: &Path) -> std::io::Result<()> {
    let json =
        config_schema_json().map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e))?;
    std::fs::write(out_path, json)
}

/// `schema_with` helper for fields of type `toml::Value` — free-form TOML
/// content that is opaque to the schema (e.g. `[shell_environment_policy]`,
/// client-written `hints`). Schema: any JSON value.
pub fn any_toml_value_schema(_gen: &mut SchemaGenerator) -> Schema {
    Schema::try_from(Value::Bool(true)).expect("bool is a valid JSON Schema")
}

/// Self-contained HTML reference for the config surface (apex-33z).
/// Declared here (mirroring the `#[path]` include of `mod tests` below) so
/// the HTML lane stays inside this file's pathspec.
#[path = "config_schema_html.rs"]
pub mod html;

#[cfg(test)]
#[path = "config_schema_tests.rs"]
mod tests;
