#!/usr/bin/env python3
"""Generate cases/rt-m6.json: the FULL live-catalog sweep (item-11 shape).

Fetches /v1/models from the proxy (CODEX_LLM_PROXY_KEY), drops embedding
models (no chat turns), and emits one row + the standard 2 wire asserts per
model: backend path (/v1/messages for claude*, /v1/responses otherwise per
the live config default_api_backend) + body.model echo. An assert that
starts failing = a config/wire change to adjudicate, which is the point of
the sign-off sweep.

Usage:  python3 smoke/redteam/gen-matrix.py
        python3 -u smoke/redteam/run.py RT-M6 --budget 120

The generated file is a build artifact of this script: do not hand-edit,
regenerate after catalog changes.
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.environ.get(
    "GROK_PROXY_MATRIX_OUT", os.path.join(HERE, "cases", "rt-m6.json"))
MODELS_URL = os.environ.get(
    "GROK_PROXY_MODELS_URL", "https://llm-proxy-api.ai.eng.netapp.com/v1/models")


def embedding_model(mid):
    low = mid.lower()
    return ("embedding" in low or "colbert" in low)


def expected_path(mid):
    return "/v1/messages" if mid.startswith("claude") else "/v1/responses"


def main():
    key = os.environ.get("CODEX_LLM_PROXY_KEY", "")
    if not key:
        print("FATAL: CODEX_LLM_PROXY_KEY not in env", file=sys.stderr)
        return 1
    # HYG-3: the auth header arrives on curl's stdin via `--config -`, so
    # `ps` only ever sees: curl -s --config - <MODELS_URL> (no key in argv).
    out = subprocess.run(
        ["curl", "-s", "--config", "-", MODELS_URL],
        input='header = "Authorization: Bearer %s"\n' % key,
        capture_output=True, text=True, check=True).stdout
    data = json.loads(out).get("data", [])
    ids = sorted(mid for mid in (m["id"] for m in data) if not embedding_model(mid))
    skipped = len(data) - len(ids)

    rows, wire = [], []
    for mid in ids:
        rows.append({"model": mid, "prompt": "Reply with exactly: HT1-OK"})
        for path in ({"path": "$.path", "eq": expected_path(mid)},
                     {"path": "$.body.model", "eq": mid}):
            wire.append({"kind": "field", "file": "req-*.json",
                         "where": {"method": "POST", "$.body.model": mid},
                         "row_model": mid, **path})

    case = {
        "id": "RT-M6",
        "title": ("GENERATED by gen-matrix.py (do not hand-edit): full live-catalog "
                  "sweep, one fresh headless turn per model; sign-off pass "
                  "(release / post proxy-side change). Slim regression set = RT-M5."),
        "rows": rows,
        "watchdog_s": 300,
        "est_calls": len(rows),
        "row_asserts": {"wire": wire},
    }
    with open(OUT, "w") as f:
        json.dump(case, f, indent=1)
        f.write("\n")
    print("wrote %s: %d rows (%d embedding models skipped)" % (OUT, len(rows), skipped))
    return 0


if __name__ == "__main__":
    sys.exit(main())
