//! GENERATED FILE — do not edit by hand (FMTL-HARDEN-1, T7).
//!
//! Generated by: `grok/plans/parity-formalism/tools/generate_outbound_lint_rules.py`
//! Source of truth: `grok/plans/parity-formalism/tools/invariant_rules.json`
//! (hard rules only; `--rules <path>` overrides the campaign location).
//! Regenerate:  `python3.14 generate_outbound_lint_rules.py --emit --worktree <worktree>`
//! Drift check: `python3.14 generate_outbound_lint_rules.py --check --worktree <worktree>`
//!
//! `HARD_RULES_CHECKSUM` is the SHA-256 (hex) of the checked-in crate fixture
//! `crates/codegen/xai-grok-sampling-types/fixtures/outbound_lint/hard_rules.json`
//! (the hard-rules projection). Two drift pins lock this file to the campaign
//! JSON: the generator `--check` (file-level, both directions) and the Rust
//! drift test in `outbound_lint.rs` (re-derives table + checksum from the
//! checked-in fixture).
/// SHA-256 (hex) of the checked-in hard-rules projection fixture.
/// Read only by the cfg(test) drift pins in `outbound_lint.rs`;
/// allowed so the non-test lib build stays warning-free.
#[allow(dead_code)]
pub const HARD_RULES_CHECKSUM: &str =
    "f93e94493e0b222ad47c198ca1d8c01154348bb300155571ce5dee943aaddc94";

/// One hard-rule row — a verbatim mirror of an `invariant_rules.json` row
/// with `severity == "hard"` (campaign order).
/// Fields `id`, `severity`, `ev`, and `description` are read only by the
/// cfg(test) drift pins; the attribute keeps the non-test lib build
/// warning-free.
#[allow(dead_code)]
pub struct HardRule {
    pub id: &'static str,
    pub class: &'static str,
    pub severity: &'static str,
    pub ev: &'static [&'static str],
    pub check: &'static str,
    pub description: &'static str,
}

/// The hard-rule table (H-1..H-6), campaign-JSON order.
pub const HARD_RULES: &[HardRule] = &[
    HardRule {
        id: "H-1",
        class: "AzStrict",
        severity: "hard",
        ev: &["EV-1"],
        check: "reasoning_content_absent_or_empty",
        description: "reasoning item in input: content ABSENT or [] - never a populated list (responses wire, strict rows)",
    },
    HardRule {
        id: "H-2",
        class: "AzStrict",
        severity: "hard",
        ev: &["EV-13", "EV-9"],
        check: "reasoning_no_encrypted_content",
        description: "OWN-origin enc only on strict rows (re-scoped per T8 OQ-T8-1 - 2.2a): a reasoning item carrying encrypted_content VIOLATES iff (a) the item carries id or mint_tag (KEY PRESENCE incl. null/empty), or (b) the carried value is not in the arm's response-side mint corpus (string values; a non-string carried value violates clause (b) by definition). Own (T0 KEEP) = no id, no mint_tag, blob in corpus - clean (EV-9 accept, on-disk mxai-c04 req-004). A2 scope = clause (a) only (3.2a)",
    },
    HardRule {
        id: "H-3",
        class: "all-responses",
        severity: "hard",
        ev: &["EV-2", "EV-3", "EV-14"],
        check: "item_id_nonempty_and_minted",
        description: "item id: when present, non-empty (all responses-wire requests); when the row is store:false Azure (AzStrict), only ids minted in this session - mint set derived from the capture's own responses",
    },
    HardRule {
        id: "H-4",
        class: "all-responses",
        severity: "hard",
        ev: &["EV-5"],
        check: "store_false",
        description: "store: false on every request body (deployment-contract standing rule)",
    },
    HardRule {
        id: "H-5",
        class: "cross-boundary",
        severity: "hard",
        ev: &["EV-4", "EV-14"],
        check: "encitem_only_to_matching_azure_row",
        description: "ROW-CLASS CLAUSE ONLY (re-scoped per T8 OQ-T8-2 - 2.2a): encitem_* ids and litellm_enc: blobs must NOT ride a non-Azure (VLLenient/Vertex) row - field-scoped (item id / encrypted_content values only; request substrings out of scope: prompt doc-text legitimately carries litellm_enc:). On AzStrict rows H-5 is SILENT (the mint-domain match is undecidable from strict-row request bytes - no mint_tag on the wire form; blob decode is O_P, out of scope). The EV-4 503 is state-conditional; the VLLenient SILENT-200 ride precedent (EV-14; the EV-12 mxai capture: prose mentions only, no carrier ids - T8 census) stays a hard violation here",
    },
    HardRule {
        id: "H-6",
        class: "all-envelope",
        severity: "hard",
        ev: &["EV-6"],
        check: "no_empty_x_litellm_tags",
        description: "no empty-string x-litellm-tags header. SCOPED: other empty-string headers are OUT of scope - ~240/400 sampled known-good requests carry empty x-grok-* headers and return 200 (mgw-toolctl-01 req-004; OQ-f)",
    },
];
