//! GENERATED FILE — do not edit by hand (FMTL-HARDEN-1, T7).
//!
//! Generated by: `grok/plans/parity-formalism/tools/generate_outbound_lint_rules.py`
//! Source of truth: `grok/plans/parity-formalism/tools/invariant_rules.json`
//! (hard rules only; `--rules <path>` overrides the campaign location).
//! Regenerate:  `python3.14 generate_outbound_lint_rules.py --emit --worktree <worktree>`
//! Drift check: `python3.14 generate_outbound_lint_rules.py --check --worktree <worktree>`
//!
//! `HARD_RULES_CHECKSUM` is the SHA-256 (hex) of the checked-in crate fixture
//! `crates/codegen/xai-grok-sampling-types/fixtures/outbound_lint/hard_rules.json`
//! (the hard-rules projection). Two drift pins lock this file to the campaign
//! JSON: the generator `--check` (file-level, both directions) and the Rust
//! drift test in `outbound_lint.rs` (re-derives table + checksum from the
//! checked-in fixture).
/// SHA-256 (hex) of the checked-in hard-rules projection fixture.
/// Read only by the cfg(test) drift pins in `outbound_lint.rs`;
/// allowed so the non-test lib build stays warning-free.
#[allow(dead_code)]
pub const HARD_RULES_CHECKSUM: &str =
    "e9c1d89bda4cbaa9736a7dfb4882fdfbb1fdc0040d9889d67927cfbabbefe6bb";

/// One hard-rule row — a verbatim mirror of an `invariant_rules.json` row
/// with `severity == "hard"` (campaign order).
/// Fields `id`, `severity`, `ev`, and `description` are read only by the
/// cfg(test) drift pins; the attribute keeps the non-test lib build
/// warning-free.
#[allow(dead_code)]
pub struct HardRule {
    pub id: &'static str,
    pub class: &'static str,
    pub severity: &'static str,
    pub ev: &'static [&'static str],
    pub check: &'static str,
    pub description: &'static str,
}

/// The hard-rule table (H-1..H-6), campaign-JSON order.
pub const HARD_RULES: &[HardRule] = &[
    HardRule {
        id: "H-1",
        class: "AzStrict",
        severity: "hard",
        ev: &["EV-1"],
        check: "reasoning_content_absent_or_empty",
        description: "reasoning item in input: content ABSENT or [] - never a populated list (responses wire, strict rows)",
    },
    HardRule {
        id: "H-2",
        class: "AzStrict",
        severity: "hard",
        ev: &["EV-13"],
        check: "reasoning_no_encrypted_content",
        description: "reasoning item carries no encrypted_content (drift guard - D-ENC strips pre-send; the EV-13 lattice proves strict rows never carry it)",
    },
    HardRule {
        id: "H-3",
        class: "all-responses",
        severity: "hard",
        ev: &["EV-2", "EV-3", "EV-14"],
        check: "item_id_nonempty_and_minted",
        description: "item id: when present, non-empty (all responses-wire requests); when the row is store:false Azure (AzStrict), only ids minted in this session - mint set derived from the capture's own responses",
    },
    HardRule {
        id: "H-4",
        class: "all-responses",
        severity: "hard",
        ev: &["EV-5"],
        check: "store_false",
        description: "store: false on every request body (deployment-contract standing rule)",
    },
    HardRule {
        id: "H-5",
        class: "cross-boundary",
        severity: "hard",
        ev: &["EV-4", "EV-9", "EV-14"],
        check: "encitem_only_to_matching_azure_row",
        description: "encitem_* ids and litellm_enc: blobs ride ONLY to the Azure row whose mint domain matches (x-litellm-tags pin == item mint_tag); never to a VLLenient or foreign-domain row. The 503 is state-conditional (EV-4); a VLLenient ride has a SILENT-200 precedent (EV-14; EV-12 mxai) and stays a hard violation here - T8 adjudicates the drift",
    },
    HardRule {
        id: "H-6",
        class: "all-envelope",
        severity: "hard",
        ev: &["EV-6"],
        check: "no_empty_x_litellm_tags",
        description: "no empty-string x-litellm-tags header. SCOPED: other empty-string headers are OUT of scope - ~240/400 sampled known-good requests carry empty x-grok-* headers and return 200 (mgw-toolctl-01 req-004; OQ-f)",
    },
];
